### ISSUE TITLE
Did you will make it multiconverter?

### ISSUE THREAD

**Issue by Dokman** [Koward/LKBC_Converter#1]
Why don't convert to BC and more formats? like LK or Cata?

**Comment by Koward** [comment]
Hi !
Short version : they simply already exists x) !
I'm mainly playing old version servers and I wanted to make custom models for them. There are **a lot** of tools for LK but there was no LK to BC m2 converter so I wrote mine.
There are tools for Warlords of Draenor now (check M2Mod Redux) and you can convert all the way back to MoP, Cata, LK so in the end a LK to BC converter was the only tool missing to complete the chain.

Note there is not point in making a BC>LK converter (the opposite) because all BC models have been updated by Blizzard itself when updating their game.
